constraint_value(
    name = "wasm32",
    constraint_setting = "@platforms//cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "riscv32imac",
    constraint_setting = "@platforms//cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "riscv64imac",
    constraint_setting = "@platforms//cpu",
    visibility = ["//visibility:public"],
)
